name: Build Satis Repository

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Permissões necessárias para o GITHUB_TOKEN funcionar no deploy
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PHP 8.4 and Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php8.4 php8.4-cli php8.4-mbstring php8.4-xml php8.4-curl php8.4-zip unzip curl
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install Satis
        run: composer create-project composer/satis --stability=dev --keep-vcs
        
      - name: Configure SSH-key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
            ${{ secrets.SSH_PRIVATE_KEY_BROOK }}
            
      - name: Configure SSH Aliases
        run: |
          cat <<EOF >> ~/.ssh/config
          Host v2-casca
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_rsa

          Host v2-brook
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_rsa_2
          EOF

      - name: Allow SSH to try all keys
        run: |
          cat <<EOF >> ~/.ssh/config
          Host github.com
            IdentityFile ~/.ssh/id_rsa
            IdentitiesOnly no
          EOF

      - name: Build Satis
        run: php satis/bin/satis build satis.json web/

      - name: Package the generated files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web' # Pasta onde o Satis colocou os arquivos

      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
